export const GET_RESULT = 'GET_RESULT';
export const ADD_RESULT = 'ADD_RESULT';

export const GET_RESULT_INFO = 'GET_RESULT_INFO';
export const ADD_RESULT_INFO = 'ADD_RESULT_INFO';

export const GET_TEACHER_BASIC = 'GET_TEACHER_BASIC';
export const ADD_TEACHER_BASIC = 'ADD_TEACHER_BASIC';

export const GET_TEACHER_EDUCATION = 'GET_TEACHER_EDUCATION';
export const ADD_TEACHER_EDUCATION = 'ADD_TEACHER_EDUCATION';

export const GET_TEACHER_PROJECT = 'GET_TEACHER_PROJECT';
export const ADD_TEACHER_PROJECT = 'ADD_TEACHER_PROJECT';

export const GET_TEACHER_PUBLICATION = 'GET_TEACHER_PUBLICATION';
export const ADD_TEACHER_PUBLICATION = 'ADD_TEACHER_PUBLICATION';

export const GET_TEACHER_RESEARCH = 'GET_TEACHER_RESEARCH';
export const ADD_TEACHER_RESEARCH = 'ADD_TEACHER_RESEARCH';

export const GET_TEACHER_AWARD = 'GET_TEACHER_AWARD';
export const ADD_TEACHER_AWARD = 'ADD_TEACHER_AWARD';

export const GET_STUDENT_BASIC = 'GET_STUDENT_BASIC';
export const ADD_STUDENT_BASIC = 'ADD_STUDENT_BASIC';

export const GET_STUDENT_EDUCATION = 'GET_STUDENT_EDUCATION';
export const ADD_STUDENT_EDUCATION = 'ADD_STUDENT_EDUCATION';

export const GET_STUDENT_PROJECT = 'GET_STUDENT_PROJECT';
export const ADD_STUDENT_PROJECT = 'ADD_STUDENT_PROJECT';

export const GET_STUDENT_PUBLICATION = 'GET_STUDENT_PUBLICATION';
export const ADD_STUDENT_PUBLICATION = 'ADD_STUDENT_PUBLICATION';

export const GET_STUDENT_RESEARCH = 'GET_STUDENT_RESEARCH';
export const ADD_STUDENT_RESEARCH = 'ADD_STUDENT_RESEARCH';

export const GET_STUDENT_AWARD = 'GET_STUDENT_AWARD';
export const ADD_STUDENT_AWARD = 'ADD_STUDENT_AWARD';
